# Generated by Django 4.2.11 on 2024-04-25 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='babiesform',
            name='comment',
        ),
    ]
