# Generated by Django 5.0.4 on 2024-05-08 06:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitter_arrival',
            name='timein',
        ),
        migrations.AddField(
            model_name='sitter_arrival',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='amount_received',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='payee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='day.babiesform'),
        ),
        migrations.AlterField(
            model_name='sitter_arrival',
            name='date_of_arrival',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sitterform',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sitterpayment',
            name='amount',
            field=models.IntegerField(default=3000),
        ),
        migrations.AlterField(
            model_name='sitterpayment',
            name='sitter_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='day.sitter_arrival'),
        ),
        migrations.AlterField(
            model_name='usedlog',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='day.procurement'),
        ),
        migrations.AlterField(
            model_name='usedlog',
            name='quantity_issued',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='usedlog',
            name='usage_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
