# Generated by Django 5.0.4 on 2024-04-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitterform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('next_of_kin', models.CharField(blank=True, max_length=200, null=True)),
                ('national_identification_number', models.CharField(blank=True, max_length=200, null=True)),
                ('recommenders_name', models.CharField(blank=True, max_length=200, null=True)),
                ('religon', models.CharField(blank=True, max_length=200, null=True)),
                ('level_of_education', models.CharField(blank=True, choices=[('diploma', 'Diploma'), ('highschool', 'Highschool')], max_length=200, null=True)),
                ('sitter_number', models.IntegerField(default=0)),
                ('contacts', models.CharField(max_length=200)),
            ],
        ),
    ]
