# Generated by Django 4.2.11 on 2024-04-26 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departure',
            name='babys_number',
        ),
    ]
