# Generated by Django 5.0.4 on 2024-04-30 16:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitterpayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('numbers_of_babies_attended_to', models.IntegerField(default=0)),
                ('sitter_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='day.sitterform')),
            ],
        ),
    ]
