# Generated by Django 4.2.11 on 2024-04-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0002_remove_babiesform_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='babiesform',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
