# Generated by Django 5.0.4 on 2024-05-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0002_remove_sitter_arrival_timein_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='babiesform',
            old_name='timein',
            new_name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='babiesform',
            name='date',
        ),
        migrations.RemoveField(
            model_name='sitter_departure',
            name='timeout',
        ),
        migrations.AddField(
            model_name='babiesform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sitter_departure',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitter_departure',
            name='date_of_departure',
            field=models.DateField(),
        ),
    ]
