# Generated by Django 4.2.11 on 2024-04-26 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0002_remove_departure_babys_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='departure',
            name='baby_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='day.babiesform'),
            preserve_default=False,
        ),
    ]
