# Generated by Django 5.0.3 on 2024-04-29 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0002_remove_sitter_arrival_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procurement',
            name='net_stock',
        ),
        migrations.RemoveField(
            model_name='procurement',
            name='price',
        ),
        migrations.RemoveField(
            model_name='procurement',
            name='total_cost',
        ),
        migrations.AddField(
            model_name='procurement',
            name='received_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='Usedlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_issued', models.IntegerField(default=0)),
                ('usage_date', models.DateField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='day.procurement')),
            ],
        ),
    ]
