# Generated by Django 5.0.4 on 2024-05-08 08:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0003_rename_timein_babiesform_arrival_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departure',
            name='date',
        ),
        migrations.RemoveField(
            model_name='departure',
            name='timeout',
        ),
        migrations.AddField(
            model_name='departure',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='departure',
            name='date_of_departure',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
