# Generated by Django 5.0.4 on 2024-04-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0003_alter_sitterform_level_of_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitterform',
            name='level_of_education',
            field=models.CharField(blank=True, choices=[('diploma', 'Diploma'), ('highschool', 'Highschool'), ('others', 'Others')], max_length=200, null=True),
        ),
    ]
