# Generated by Django 5.0.4 on 2024-04-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0004_alter_sitterform_level_of_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='babiesform',
            name='name_of_the_person_that_taken_a_child',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
