# Generated by Django 4.2.11 on 2024-04-25 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0004_remove_babiesform_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='babiesform',
            old_name='name_of_the_person_that_has_taken_a_child',
            new_name='Pickers_name',
        ),
        migrations.RenameField(
            model_name='babiesform',
            old_name='name_of_the_person_brought_by_the_baby',
            new_name='care_taker',
        ),
    ]
