# Generated by Django 5.0.4 on 2024-04-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0005_babiesform_name_of_the_person_that_taken_a_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babiesform',
            name='timein',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='babiesform',
            name='timeout',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
