# Generated by Django 5.0.4 on 2024-05-09 17:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0005_alter_babiesform_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='actual_amount',
            field=models.IntegerField(choices=[(10000, '10000'), (15000, '15000'), (300000, '300000'), (450000, '450000')], default=0),
        ),
        migrations.AlterField(
            model_name='usedlog',
            name='usage_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
