# Generated by Django 5.0.4 on 2024-04-22 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0006_alter_babiesform_timein_alter_babiesform_timeout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='babiesform',
            name='c_fees',
        ),
        migrations.AddField(
            model_name='payment',
            name='payee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='day.babiesform'),
        ),
    ]
