# Generated by Django 5.0.4 on 2024-05-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0006_alter_payment_actual_amount_alter_usedlog_usage_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitterpayment',
            old_name='amount',
            new_name='amount_paid',
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='quantity_sold',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
