# Generated by Django 5.0.4 on 2024-04-22 17:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0007_remove_babiesform_c_fees_payment_payee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='babiesform',
            old_name='name_of_the_person_that_taken_a_child',
            new_name='name_of_the_person_that_has_taken_a_child',
        ),
        migrations.AddField(
            model_name='babiesform',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sitterform',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
