# Generated by Django 5.0.4 on 2024-05-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0007_rename_amount_sitterpayment_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitterform',
            name='level_of_education',
            field=models.CharField(choices=[('Diploma', 'Diploma'), ('Highschool certificate', 'Highschool certificate'), ('Others', 'Others')], max_length=200),
        ),
    ]
