# Generated by Django 5.0.4 on 2024-05-12 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0008_alter_sitterform_level_of_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Period_of_stay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='day.categorystay'),
        ),
        migrations.AlterField(
            model_name='sitterform',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('Female', 'Female')], max_length=100),
        ),
    ]
