# Generated by Django 5.0.4 on 2024-05-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0009_payment_period_of_stay_alter_sitterform_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitter_departure',
            name='status',
            field=models.CharField(choices=[('Offduty', 'Offduty')], max_length=100, null=True),
        ),
    ]
