# Generated by Django 5.0.4 on 2024-05-14 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0010_sitter_departure_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='babiesform',
            old_name='babys_number',
            new_name='babynumber',
        ),
        migrations.RenameField(
            model_name='departure',
            old_name='babys_name',
            new_name='babyname',
        ),
    ]
